In [173]:
import numpy as np

In [72]:
np.__version__

'2.1.0'

In [73]:
#Creating array

In [74]:
list1=[1,2,3,4]
print(list1)

[1, 2, 3, 4]


In [75]:
arr=np.array(list1)
arr

array([1, 2, 3, 4])

In [76]:
arr.dtype

dtype('int64')

In [77]:
arr.ndim

1

In [78]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
arr.ndim

2

In [80]:
#numpy array attributes

In [81]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
arr.ndim

2

In [83]:
arr.shape

(2, 3)

In [84]:
arr.size

6

In [85]:
arr.dtype

dtype('int64')

In [86]:
#Array Initialization Method

In [87]:
zero_arr=np.zeros((2,3))
zero_arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [88]:
one_arr=np.ones((3,2))
one_arr

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [89]:
full_arr=np.full((3,3),5)
full_arr

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [90]:
id_arr=np.eye(2)
id_arr

array([[1., 0.],
       [0., 1.]])

In [91]:
np.empty(3)

array([1., 2., 4.])

In [92]:
np.random.rand(4,2)

array([[0.26992605, 0.04392414],
       [0.75781077, 0.48540182],
       [0.15433779, 0.9320155 ],
       [0.41228993, 0.66707121]])

In [93]:
np.random.randn(3)

array([0.48168734, 2.11536931, 2.71987529])

In [94]:
np.random.randint(1,10,(3,2))

array([[6, 2],
       [2, 9],
       [7, 3]], dtype=int32)

In [95]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [96]:
np.linspace(1,20,3)

array([ 1. , 10.5, 20. ])

In [97]:
#Array Indexing and Slicing

In [98]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [99]:
a[3] 

np.int64(4)

In [100]:
a[-1]

np.int64(5)

In [101]:
a[0:4]

array([1, 2, 3, 4])

In [102]:
a[1::2]

array([2, 4])

In [103]:
arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [104]:
arr2[0][2]

np.int64(3)

In [105]:
arr2[1][1]

np.int64(5)

In [106]:
arr2[:, 0]

array([1, 4])

In [107]:
arr2[1:]

array([[4, 5, 6]])

In [108]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [109]:
arr3[1]

array([4, 5, 6])

In [110]:
arr3[0][2]

np.int64(3)

In [111]:
arr3[:, 0]

array([1, 4, 7])

In [112]:
arr3[:,1:2]

array([[2],
       [5],
       [8]])

In [113]:
arr3[2:,1:2]

array([[8]])

In [114]:
#Array Reshaping and Flattening

In [115]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [116]:
arr.shape

(6,)

In [117]:
reshape1=arr.reshape((6,1))
reshape1

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [118]:
reshape1.shape

(6, 1)

In [119]:
reshape1=arr.reshape((2,3))
reshape1

array([[1, 2, 3],
       [4, 5, 6]])

In [120]:
reshape1=reshape1.flatten()
reshape1

array([1, 2, 3, 4, 5, 6])

In [121]:
#Array Stacking and Splitting

In [122]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [123]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [124]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [125]:
c=np.array([a,b])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [126]:
hsplit=np.hsplit(c,3)
hsplit

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [127]:
vsplit=np.vsplit(c,2)
vsplit

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [128]:
#Mathematical Operations on Array

In [129]:
a = np.array([10,20,40,-30])
a

array([ 10,  20,  40, -30])

In [130]:
a+10

array([ 20,  30,  50, -20])

In [131]:
a-5

array([  5,  15,  35, -35])

In [132]:
a*2

array([ 20,  40,  80, -60])

In [133]:
a/10

array([ 1.,  2.,  4., -3.])

In [134]:
a=np.square(a)
a

array([ 100,  400, 1600,  900])

In [135]:
np.sqrt(a)

array([10., 20., 40., 30.])

In [136]:
#Mathematical operations on multiple arrays

In [137]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a,b

(array([1, 2, 3]), array([4, 5, 6]))

In [138]:
np.add(a,b)

array([5, 7, 9])

In [139]:
np.subtract(a,b)

array([-3, -3, -3])

In [140]:
np.multiply(a,b)

array([ 4, 10, 18])

In [141]:
np.divide(a,b)

array([0.25, 0.4 , 0.5 ])

In [142]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [143]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [144]:
a.T

array([[1, 3],
       [2, 4]])

In [145]:
t=np.array([[1,2,3],[4,5,6]])
t

array([[1, 2, 3],
       [4, 5, 6]])

In [146]:
t.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [147]:
#Statistical Functions

In [148]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [149]:
np.sum(a)

np.int64(21)

In [150]:
np.mean(a)

np.float64(3.5)

In [151]:
np.median(a)

np.float64(3.5)

In [152]:
np.std(a)

np.float64(1.707825127659933)

In [153]:
np.min(a)

np.int64(1)

In [154]:
np.max(a)

np.int64(6)

In [155]:
#Array Comparision

In [156]:
a = np.array([1,5,3])
b = np.array([4,5,6])
a,b

(array([1, 5, 3]), array([4, 5, 6]))

In [157]:
a==b

array([False,  True, False])

In [158]:
np.array_equal(a,b)

False

In [159]:
#Broadcasting

In [160]:
a = np.array([1,2,3,4])
b = np.array([5])
a+b

array([6, 7, 8, 9])

In [161]:
c = np.array([[1,2,3], [4,5,6]])
d = np.array([10,20,30])
c+d

array([[11, 22, 33],
       [14, 25, 36]])

In [162]:
#Handling nan and inf

In [163]:
data1 =  np.array([1,2, np.nan, 4, np.inf])
print(data1)

[ 1.  2. nan  4. inf]


In [164]:
np.isnan(data1)

array([False, False,  True, False, False])

In [165]:
np.nan_to_num(data1)

array([1.00000000e+000, 2.00000000e+000, 0.00000000e+000, 4.00000000e+000,
       1.79769313e+308])

In [166]:
#Save and LOad data

In [167]:
arr = np.array([1,0,0,8])
arr

array([1, 0, 0, 8])

In [168]:
np.save('my_array.npy',arr)

In [169]:
loaded_arr = np.load('my_array.npy')
loaded_arr

array([1, 0, 0, 8])